version: "3.9"
services:
  api:
    build: .
    ports:
      - "8001:8000"
    container_name: sh_runner_daemon
    env_file:
      - .env
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        uvicorn service.main:app --host 0.0.0.0 --port 8000 --reload
    restart: on-failure
    volumes:
      - ./.:/app

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - pr_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - gr_data:/var/lib/grafana

volumes:
  gr_data:
  pr_data:
